### ISSUE TITLE
Fix a variable for the role robertdebock.users

### ISSUE THREAD

**Issue by kksudo** [robertdebock/ansible-development-environment#1]
There the variable `authorized_key` is defined in [inventory/group_vars/all.yml](https://github.com/robertdebock/ansible-development-environment/blob/master/inventory/group_vars/all.yml#L16), but after apply the 
 robertdebock.users role, ansible returned the error:
```
fatal: [test-machine]: FAILED! => {"msg": "'dict object' has no attribute 'authorized_keys'"}
```

Should update variable authorized_key->authorized_key**s** in `inventory/group_vars/all.yml` for role `robertdebock.users`

**Comment by kksudo** [comment]
Mismatched version of user role from galaxy and role in repo. Sorry.

**Comment by robertdebock** [comment]
No worries, thanks anyway for the feedback.
